pipeline {

    agent any

    environment {
        DOCKERHUB_USERNAME = "devipriyadp1"
        BACKEND_IMAGE = "aldi-lidl-backend"
        FRONTEND_IMAGE = "aldi-lidl-frontend"
    }

    stages {

        stage('Clone Repository') {
            steps {
                git branch: 'main',
                url: 'https://github.com/Devipriyakarunagaran/Super_Offer_Flat_AI.git'
            }
        }

        stage('Build Backend Image') {
            steps {
                sh '''
                docker build -t $DOCKERHUB_USERNAME/$BACKEND_IMAGE:latest ./backend
                '''
            }
        }

        stage('Build Frontend Image') {
            steps {
                sh '''
                docker build -t $DOCKERHUB_USERNAME/$FRONTEND_IMAGE:latest ./frontend
                '''
            }
        }

        stage('DockerHub Login') {
            steps {
                withCredentials([usernamePassword(
                    credentialsId: 'dockerhub-creds',
                    usernameVariable: 'DOCKER_USER',
                    passwordVariable: 'DOCKER_PASS'
                )]) {
                    sh '''
                    echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
                    '''
                }
            }
        }

        stage('Push Backend Image') {
            steps {
                sh '''
                docker push $DOCKERHUB_USERNAME/$BACKEND_IMAGE:latest
                '''
            }
        }

        stage('Push Frontend Image') {
            steps {
                sh '''
                docker push $DOCKERHUB_USERNAME/$FRONTEND_IMAGE:latest
                '''
            }
        }
    }

    post {
        success {
            echo '✅ Pipeline completed successfully!'
        }

        failure {
            echo '❌ Pipeline failed. Check logs.'
        }
    }
}
