pipeline {

    agent any

    environment {
        DOCKERHUB_USERNAME = "devipriyadp1"
        BACKEND_IMAGE = "aldi-lidl-backend"
        FRONTEND_IMAGE = "aldi-lidl-frontend"
    }

    stages {

        stage('Clone Repository') {
            steps {
                git branch: 'main',
                url: 'https://github.com/Devipriyakarunagaran/Super_Offer_Flat_AI.git'
            }
        }

        stage('Get Git Commit ID') {
            steps {
                script {
                    env.GIT_COMMIT_SHORT = sh(
                        script: "git rev-parse --short HEAD",
                        returnStdout: true
                    ).trim()
                }
            }
        }

        stage('Build Backend Image') {
            steps {
                sh '''
                docker build -t $DOCKERHUB_USERNAME/$BACKEND_IMAGE:$GIT_COMMIT_SHORT ./backend
                '''
            }
        }

        stage('Build Frontend Image') {
            steps {
                sh '''
                docker build -t $DOCKERHUB_USERNAME/$FRONTEND_IMAGE:$GIT_COMMIT_SHORT ./frontend
                '''
            }
        }

        stage('DockerHub Login') {
            steps {
                withCredentials([usernamePassword(
                    credentialsId: 'dockerhub-creds',
                    usernameVariable: 'DOCKER_USER',
                    passwordVariable: 'DOCKER_PASS'
                )]) {
                    sh '''
                    echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
                    '''
                }
            }
        }

        stage('Push Backend Image') {
            steps {
                sh '''
                docker push $DOCKERHUB_USERNAME/$BACKEND_IMAGE:$GIT_COMMIT_SHORT
                '''
            }
        }

        stage('Push Frontend Image') {
            steps {
                sh '''
                docker push $DOCKERHUB_USERNAME/$FRONTEND_IMAGE:$GIT_COMMIT_SHORT
                '''
            }
        }

        stage('Update Helm Values') {

            steps {

                sh '''
                sed -i "s|image:.*backend.*|image: devipriyadp1/aldi-lidl-backend:${GIT_COMMIT_SHORT}|g" aldi-lidl/values.yaml

                sed -i "s|image:.*frontend.*|image: devipriyadp1/aldi-lidl-frontend:${GIT_COMMIT_SHORT}|g" aldi-lidl/values.yaml
                '''
            }

        }

        stage('Commit Helm Changes') {

            steps {
                sh '''
                git config user.email "jenkins@ci.com"
                git config user.name "jenkins"

                git add .
                git commit -m "auto update image tags: ${GIT_COMMIT_SHORT}" || true
                git push
                '''
            }
        }
    }

    post {
        success {
            echo "✅ Pipeline successful - GitOps updated"
        }

        failure {
            echo "❌ Pipeline failed"
        }
    }
}
